# Use .NET SDK to build your app
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy project file and restore packages
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of your code and publish the app
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Use a smaller runtime image to run the app
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./

# Tell Docker which port the app listens to
ENV ASPNETCORE_URLS=http://+:$PORT
EXPOSE 80

# Start the app (change DLL name!)
ENTRYPOINT ["dotnet", "HouseOfWani.dll"]
